{% set name = "mdformat" %}
{% set version = "0.7.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat-{{ version }}.tar.gz
  
  sha256: a7d22df9802383432367864da907d2d147485b5cb6872e2d66937c1333e4d58a

build:
  number: 0
  noarch: python
  entry_points:
    - mdformat = mdformat.__main__:run
  script: {{ PYTHON }} -m pip install . -vv

# Check [project.dependencies] in
#   https://github.com/executablebooks/mdformat/blob/master/pyproject.toml
requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - pip
  run:
    - python >={{ python_min }}
    - markdown-it-py >=1.0.0,<4.0.0
    - tomli >=1.1.0
    - importlib-metadata >=3.6.0

test:
  imports:
    - mdformat
    - mdformat.codepoints
  commands:
    - pip check
    - mdformat --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/executablebooks/mdformat
  summary: CommonMark compliant Markdown formatter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
